from Transaksi import Transaksi

def main():
    daftar = []

    # === 5 DATA AWAL ===
    t1 = Transaksi()
    t1.set_id_transaksi(101)
    t1.set_nama_produk("Laptop")
    t1.set_brand("Asus")
    t1.set_kode("AS123")
    t1.set_harga(8000000)
    t1.set_deskripsi("Laptop Gaming")
    t1.set_id_toko(1)
    t1.set_nama_toko("Toko Elektronik Jaya")
    t1.set_pemilik("Budi")
    t1.set_alamat("Jl. Merdeka No. 10")
    t1.set_no_izin_usaha("IZN-001")
    t1.set_stok(10)
    t1.set_jumlah_barang(2)
    t1.set_metode_pembayaran("Cash")
    daftar.append(t1)

    t2 = Transaksi()
    t2.set_id_transaksi(102)
    t2.set_nama_produk("Smartphone")
    t2.set_brand("Samsung")
    t2.set_kode("SM456")
    t2.set_harga(5000000)
    t2.set_deskripsi("HP Android")
    t2.set_id_toko(2)
    t2.set_nama_toko("Gadget Center")
    t2.set_pemilik("Andi")
    t2.set_alamat("Jl. Sudirman No. 5")
    t2.set_no_izin_usaha("IZN-002")
    t2.set_stok(20)
    t2.set_jumlah_barang(1)
    t2.set_metode_pembayaran("Transfer")
    daftar.append(t2)

    t3 = Transaksi()
    t3.set_id_transaksi(103)
    t3.set_nama_produk("Televisi")
    t3.set_brand("LG")
    t3.set_kode("TV789")
    t3.set_harga(4000000)
    t3.set_deskripsi("Smart TV 32 inch")
    t3.set_id_toko(3)
    t3.set_nama_toko("Electronic Mart")
    t3.set_pemilik("Siti")
    t3.set_alamat("Jl. Asia Afrika No. 7")
    t3.set_no_izin_usaha("IZN-003")
    t3.set_stok(5)
    t3.set_jumlah_barang(1)
    t3.set_metode_pembayaran("E-Wallet")
    daftar.append(t3)

    t4 = Transaksi()
    t4.set_id_transaksi(104)
    t4.set_nama_produk("Kulkas")
    t4.set_brand("Sharp")
    t4.set_kode("RF111")
    t4.set_harga(3500000)
    t4.set_deskripsi("2 pintu hemat listrik")
    t4.set_id_toko(4)
    t4.set_nama_toko("Appliance Store")
    t4.set_pemilik("Dewi")
    t4.set_alamat("Jl. Diponegoro No. 20")
    t4.set_no_izin_usaha("IZN-004")
    t4.set_stok(7)
    t4.set_jumlah_barang(1)
    t4.set_metode_pembayaran("Cash")
    daftar.append(t4)

    t5 = Transaksi()
    t5.set_id_transaksi(105)
    t5.set_nama_produk("Headphone")
    t5.set_brand("Sony")
    t5.set_kode("HD999")
    t5.set_harga(1200000)
    t5.set_deskripsi("Noise Cancelling")
    t5.set_id_toko(5)
    t5.set_nama_toko("Audio Hub")
    t5.set_pemilik("Fajar")
    t5.set_alamat("Jl. Braga No. 12")
    t5.set_no_izin_usaha("IZN-005")
    t5.set_stok(15)
    t5.set_jumlah_barang(3)
    t5.set_metode_pembayaran("Transfer")
    daftar.append(t5)

    # Cetak tabel pertama kali
    Transaksi.print_table(daftar)

    # Loop input user
    while True:
        lanjut = input("\nTambah data transaksi baru? (y/n): ")
        if lanjut.lower() != "y":
            break

        t = Transaksi()
        t.set_id_transaksi(int(input("ID Transaksi : ")))
        t.set_nama_produk(input("Nama Produk  : "))
        t.set_brand(input("Merk Produk  : "))
        t.set_kode(input("No Seri      : "))
        t.set_harga(int(input("Harga Produk : ")))
        t.set_deskripsi(input("Deskripsi    : "))
        t.set_id_toko(int(input("ID Toko      : ")))
        t.set_nama_toko(input("Nama Toko    : "))
        t.set_pemilik(input("Pemilik      : "))
        t.set_alamat(input("Alamat Toko  : "))
        t.set_no_izin_usaha(input("No Izin Usaha: "))
        t.set_stok(int(input("Stok         : ")))
        t.set_jumlah_barang(int(input("Jumlah Beli  : ")))
        t.set_metode_pembayaran(input("Metode Bayar : "))

        daftar.append(t)
        print("\nTransaksi berhasil ditambahkan!\n")
        Transaksi.print_table(daftar)

if __name__ == "__main__":
    main()